version: '3.1'

services:

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./.docker/mongodb/db:/data/db
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
